name: 🎉✨ Pull Request
description: Pull Request for `SpectraFit`
title: "[PR]: "
assignees:
  - Anselmoo
body:
  - type: checkboxes
    attributes:
      label: Is there an existing Pull Request for this?
      description: |
        Please search to see if an [Pull Request](https://github.com/Anselmoo/spectrafit/pulls) already exists for the 🎉✨ PR you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submitting this Pull Request!
  - type: textarea
    attributes:
      label: Details
      description: A concise description of the PR.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Testing
      description: |
        Please select the testing framework(s) you are using.
      options:
        - label: Pre-Commit
          required: true
        - label: Pytest
          required: false
        - label: Coverage
          required: false
        - label: mkdocs
          required: false
  - type: textarea
    attributes:
      label: ⚙️ Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Python**: 3.8.11
          - **spectrafit**: v0.4.0
      value: |
        - OS:
        - Python:
        - spectrafit:
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Anselmoo/spectrafit/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
