name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
template: |
  # :compass: What's Changed
  $CHANGES

  # :package: Full Changelog
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  # :gear: Who Contributes
  $CONTRIBUTORS

categories:
  - title: ":trophy: Milestone"
    label: "milestone"
  - title: ":rocket: New"
    label: "enhancement"
  - title: ":computer: Codesspaces"
    label: "codespaces"
  - title: ":bug: Bug Fixes"
    label: "bug"
  - title: ":toolbox: Maintenance"
    label: ["maintenance", "codeowners"]
  - title: ":snake: Python"
    label: "python"
  - title: ":octocat: Github Actions"
    label: "github-actions"
  - title: ":card_index_dividers: Documentation"
    label: "documentation"
  - title: ":link: Dependency Updates"
    label: "dependencies"
  - title: ":microscope: Testing & Coverage"
    label: "testing"
  - title: ":wave: Welcome"
    label: "good first issue"
  - title: ":lock: Security"
    label: "security"
  - title: ":memo: Changelog"
    label: "changelog"
  - title: ":receipt: Forms"
    label: "forms"
  - title: ":whale: Docker"
    label: "docker"
  - title: ":package: Vendor"
    label: "vendor"

version-resolver:
  major:
    labels:
      - "milestone"
  minor:
    labels:
      - "enhancement"
      - "feature"
      - "codeowners"
  patch:
    labels:
      - "codespaces"
      - "docker"
      - "maintenance"
      - "documentation"
      - "dependencies"
      - "forms"
      - "github-actions"
      - "security"
      - "testing"
      - "good first issue"
      - "changelog"
      - "vendor"

exclude-labels:
  - "skip-changelog"
  - "duplicate"
  - "invalid"
  - "wontfix"
  - "question"

exclude-contributors:
  - dependabot[bot]
  - ImgBotApp
  - dependabot
  - imgbot
  - pre-commit-ci
  - pre-commit-ci[bot]
