changelog:
  categories:
    - title: "🏆 Milestone"
      labels: "milestone"
    - title: "🚀 New"
      labels: "enhancement"
    - title: "💻 New"
      labels: "codespaces"
    - title: "🐛 Bug Fixes"
      labels: "bug"
    - title: "🧰 Maintenance"
      labels: "maintenance"
    - title: ":octocat: Github Actions"
      labels: "github-actions"
    - title: "🗂 Documentation"
      labels: "documentation"
    - title: "🔗 Dependency Updates"
      labels: "dependencies"
    - title: "🔬 Testing & Coverage"
      labels: "testing"
    - title: "👋 Welcome"
      labels: "good first issue"
    - title: "🔒 Security"
      labels:
        - "security"
        - "dependabot"
    - title: "🚨 Breaking Changes"
      labels: "breaking"
    - title: "📝 Changelog"
      labels: "changelog"
