name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
template: |
  # 🧭 What's Changed
  $CHANGES

  # 📦 Full Changelog
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  # ⚙️ Who Contributes
  $CONTRIBUTORS

categories:
  - title: "🏆 Milestone"
    label: "milestone"
  - title: "🚀 New"
    label: "enhancement"
  - title: "💻 Codesspaces"
    label: "codespaces"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "🧰 Maintenance"
    label: "maintenance"
  - title: ":octocat: Github Actions"
    label: "github-actions"
  - title: "🗂 Documentation"
    label: "documentation"
  - title: "🔗 Dependency Updates"
    label: "dependencies"
  - title: "🔬 Testing & Coverage"
    label: "testing"
  - title: "👋 Welcome"
    label: "good first issue"
  - title: "🔒 Security"
    label: "security"
  - title: "📝 Changelog"
    label: "changelog"
  - title: "🧾 Forms"
    label: "forms"
  - title: "🐳 Docker"
    label: "docker"

version-resolver:
  major:
    labels:
      - "milestone"
  minor:
    labels:
      - "enhancement"
      - "feature"
      - "codeowners"
  patch:
    labels:
      - "codespaces"
      - "docker"
      - "maintenance"
      - "documentation"
      - "dependencies"
      - "forms"
      - "github-actions"
      - "security"
      - "testing"
      - "good first issue"

exclude-labels:
  - "skip-changelog"
  - "duplicate"
  - "invalid"
  - "wontfix"
  - "question"

exclude-contributors:
  - dependabot[bot]
  - ImgBotApp
  - dependabot
  - imgbot
  - pre-commit-ci
  - pre-commit-ci[bot]
