image: python:3.13

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - local: .gitlab/ci/pre-commit.yml
  - local: .gitlab/ci/linting.yml
  - local: .gitlab/ci/secret-detection.yml
  - local: .gitlab/ci/testing.yml
  - local: .gitlab/ci/docs.yml
  - local: .gitlab/ci/deploy.yml
  - local: .gitlab/ci/release.yml
  - local: .gitlab/ci/github-mirror.yml

stages:
  - pretest
  - test
  - deploy
  - prepare
  - release
  - mirror

variables:
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  PACKAGE_REGISTRY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages
  PYTHONPATH: ${CI_PROJECT_DIR}
  RUFF_VERSION: 0.11.12
  UV_VERSION: 0.7.8
  BASE_LAYER: bookworm-slim
  UV_LINK_MODE: copy

cache:
  paths:
    - .cache/pip
    - .cache/uv
    - uv.lock
