repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-toml
        exclude: poetry.lock
      - id: check-json
        exclude: .devcontainer/devcontainer.json
      - id: check-symlinks
      - id: end-of-file-fixer
        exclude: docs/images/logo.svg
      - id: trailing-whitespace
      - id: check-ast
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]
        exclude: \.ipynb
  - repo: https://github.com/psf/black.git
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.1.0]
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: [toml==0.10.2]
  - repo: https://github.com/PyCQA/flake8.git
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ^spectrafit/test/, ^examples/
        entry: flake8  --max-doc-length 100 --max-line-length  88 --ignore E203,W503,W605
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        additional_dependencies:
          [
            types-toml==0.10.8.2,
            types-PyYAML==6.0.12.4,
            types-tabulate==0.9.0.0,
            types-mock==5.0.0.2,
            pandas==1.5.0,
            numpy==1.23.4,
            pydantic==1.10.1,
            pytest==7.1.3,
          ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: [toml==0.10.2]
  - repo: https://github.com/PyCQA/pylint
    rev: "v2.17.0"
    hooks:
      - id: pylint
        additional_dependencies: [toml==0.10.2, numpy==1.23.4, pydantic==1.10.1]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.6"
    hooks:
      - id: prettier
        exclude: docs/examples/example9_1.md
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.0
    hooks:
      - id: jupytext
        args: [--from, ipynb, --to, md, --pipe, black]
        additional_dependencies: [black==23.1.0]
