repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-toml
      - id: check-json
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/psf/black.git
    rev: 21.10b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==21.9b0]
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.10.0
    hooks:
      - id: isort
        additional_dependencies: [toml==0.10.2]
  - repo: https://github.com/PyCQA/flake8.git
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^spectrafit/test/, ^examples/
        additional_dependencies: [flake8-docstrings]
        entry: flake8 --docstring-convention google --max-doc-length 100 --max-line-length  88 --ignore E203,W503,W605
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    -   id: mypy
        additional_dependencies: [types-toml==0.1.3, types-PyYAML==5.4.3, types-tabulate==0.8.0]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle
        additional_dependencies: [toml==0.10.2]
