repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        exclude: mkdocs.yaml
      - id: check-toml
      - id: check-json
        exclude: .devcontainer/devcontainer.json
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]
  - repo: https://github.com/psf/black.git
    rev: 22.8.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.6.0]
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml==0.10.2]
  - repo: https://github.com/PyCQA/flake8.git
    rev: 5.0.4
    hooks:
      - id: flake8
        exclude: ^spectrafit/test/, ^examples/
        entry: flake8  --max-doc-length 100 --max-line-length  88 --ignore E203,W503,W605
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        additional_dependencies:
          [
            types-toml==0.10.8,
            types-PyYAML==6.0.10,
            types-tabulate==0.8.11,
            numpy==1.21.4,
            pydantic==1.10.1,
          ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1 # pick a git hash / tag to point to
    hooks:
      - id: pydocstyle
        additional_dependencies: [toml==0.10.2]
  - repo: https://github.com/PyCQA/pylint
    rev: "v2.15.0"
    hooks:
      - id: pylint
        additional_dependencies: [toml==0.10.2]
