repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-toml
      - id: check-json
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/psf/black.git
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==21.7b0]
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8.git
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: ^spectrafit/test/, ^examples/
        additional_dependencies: [flake8-docstrings]
        entry: flake8 --docstring-convention google --max-line-length  88 --ignore E203,W503,W605
