coverage:
  precision: 2
  round: up
  range: "90...100"
  status:
    patch:
      default:
        target: 100%
comment:
  layout: "diff,flags,tree,betaprofiling"
  show_critical_paths: true
github_checks:
  annotations: true
