site_name: SpectraFit
site_url: https://Anselmoo.github.io/spectrafit/
site_author: Anselm Hahn
site_description: >-
  Technical documentation for SpectraFit, a Python package for fitting
# Repository
repo_name: Anselmoo/SpectraFit
repo_url: https://github.com/Anselmoo/spectrafit
edit_uri: "https://github.com/Anselmoo/spectrafit/tree/main/docs"

# Copyright
copyright: Copyright &copy; 2021 - 2023 Anselm Hahn

# Configuration
theme:
  name: material
  static_templates:
    - 404.html
  include_search_page: true
  search_index_only: true
  language: en
  features:
    - header.autohide
    - content.code.annotate
    - content.tabs.link
    - content.action.view
    - content.action.copy
    - content.code.copy
    - content.code.annotations
    - navigation.expand
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: material/github
  logo: images/logo.svg
  favicon: images/logo.svg

# Plugins
plugins:
  - search
  - mkdocstrings
  - autorefs
  - section-index
  - table-reader
  - literate-nav:
      nav_file: SUMMARY.md
  - minify:
      minify_html: true
  - mkdocs-jupyter:
      ignore_h1_titles: true
      include_source: true
      execute: true
      kernel_name: python3

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Anselmoo
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/spectrafit/
  version:
    provider: mike
    default: latest

# Extensions
markdown_extensions:
  - admonition:
  - abbr:
  - attr_list:
  - def_list:
  - footnotes:
  - meta:
  - md_in_html:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
      block_tag: "pre"
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      guess_lang: true
      extend_pygments_lang:
        - name: pycon3
          lang: pycon
          options:
            python3: true
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {
              kwds: { mode: generic },
            }
  - pymdownx.keys:
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      social_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: Anselmoo
      repo: spectrafit
  - pymdownx.mark:
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:
  - pymdownx.blocks.admonition:
  - pymdownx.blocks.details:
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: True
      combine_header_slug: True
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Getting started:
      - Installation: interface/installation.md
      - Usage: interface/usage.md
      - Features: interface/features.md
  - Examples:
      - Working via CMD:
          - Fitting of a Single Feature via Command-Line: examples/example1.md
          - JSON, TOML, YAML Inputs: examples/example2.md
          - Multi Peak Fitting: examples/example3.md
          - Working with Real Life Data: examples/example4.md
          - Working with Expressions: examples/example5.md
          - Global Fitting: examples/example6.md
          - Automatic Fitting: examples/example7.md
          - Working with Athena Data: examples/example8.md
      - Working in Jupyter Notebooks:
          - Default Plot: examples/example9_1.ipynb
          - Themes: examples/example9_2.ipynb
          - Export Results: examples/example9_3.ipynb
          - RIXS Map Visualization: examples/example9_4.ipynb
          - Using Converters as Module: examples/example9_5.ipynb
          - RIXS Global-Fitting in Jupyter: examples/example9_6.ipynb
  - Documentation:
      - Models: doc/models.md
      - Expression: doc/expression.md
      - Solvers: doc/solver.md
      - Fitting: doc/fitting.md
      - Statistics: doc/statistics.md
  - Plugins:
      - File-Format-Conversion: plugins/file_converter.md
      - Data-Format-Conversion: plugins/data_converter.md
      - Jupyter-Notebook-Integration: plugins/jupyter_interface.md
      - RIXS-Visualization: plugins/rixs_visualization.md
      - RIXS-Converter: plugins/rixs_converter.md
      - PKL-Converter and Visualizer: plugins/pkl_converter_visualization.md
      - PPTX-Converter: plugins/pptx_converter.md
  - API:
      - SpectraFit: api/spectrafit_api.md
      - Plotting: api/plotting_api.md
      - Jupyter-Notebook: api/notebook_api.md
      - Modelling: api/modelling_api.md
      - Reporting: api/reporting_api.md
      - Tools: api/tools_api.md
      - Data Model: api/data_model_api.md
      - Converters and Visualizer: api/converter_api.md
  - Support:
      - Contact: contact.md
      - License: license.md
      - Contributing: contributing.md
      - Code of Conduct: code_of_conduct.md
      - Security: security.md
  - Releases:
      - Changelog:
          - v1.x.x: changelog.md
          - v0.x.x: changelogs/v0.x.x.md
      - Contributors: contributors.md
