[[components]]
id = "p1"
model = "gaussian"

[components.parameters.amplitude]
value = 1.0
min = 0.0
max = 2.0
vary = true

[components.parameters.center]
value = 0.0
min = -2.0
max = 2.0
vary = true

[components.parameters.fwhmg]
value = 0.1
min = 0.02
max = 0.5
vary = true

[minimizer]
nan_policy = "propagate"
calc_covar = true

[optimizer]
max_nfev = 1000
method = "leastsq"
