name: 🗂 Documentation Request
description: Suggest an idea for the docs of this `SpectraFit`
title: "[Docs]: "
labels: [documentation]
assignees:
  - Anselmoo
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        1. Please also check the [issue](https://github.com/Anselmoo/spectrafit/issues).
        2. Please also check the [docs](https://anselmoo.github.io/spectrafit/).
      options:
        - label: I have searched the existing issues
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this 🗂 documentation request!
  - type: textarea
    attributes:
      label: Current Missing Information in the Docs
      description: What is missing or unclear in the docs `SpectraFit`?
      placeholder: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Anselmoo/spectrafit/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
