"""Unit tests for InitConfig and the init command scaffolding logic (Phase 2)."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

import pytest

from pydantic import ValidationError
from typer.testing import CliRunner

from spectrafit.cli.commands.scaffolding import InitConfig
from spectrafit.cli.commands.scaffolding import InitEnvironment
from spectrafit.cli.commands.scaffolding import _run_init


runner = CliRunner()


class TestInitConfig:
    """Tests for InitConfig validation."""

    @pytest.mark.unit
    def test_defaults(self, tmp_path: Path) -> None:
        cfg = InitConfig(project_name="my_project")
        assert cfg.environment == InitEnvironment.CLI
        assert cfg.overwrite is False

    @pytest.mark.unit
    def test_explicit_env(self, tmp_path: Path) -> None:
        cfg = InitConfig(project_name="p", environment=InitEnvironment.JUPYTER)
        assert cfg.environment == InitEnvironment.JUPYTER

    @pytest.mark.unit
    def test_extra_forbid(self) -> None:
        with pytest.raises(ValidationError):
            InitConfig(project_name="x", unknown_field=True)  # type: ignore[call-arg]

    @pytest.mark.unit
    @pytest.mark.parametrize(
        ("env_str", "expected"),
        [
            ("cli", InitEnvironment.CLI),
            ("jupyter", InitEnvironment.JUPYTER),
            ("both", InitEnvironment.BOTH),
        ],
    )
    def test_environment_enum_from_string(
        self, env_str: str, expected: InitEnvironment
    ) -> None:
        cfg = InitConfig(project_name="p", environment=InitEnvironment(env_str))
        assert cfg.environment == expected


class TestRunInit:
    """Tests for _run_init scaffolding logic."""

    @pytest.mark.unit
    def test_cli_creates_toml(self, tmp_path: Path) -> None:
        cfg = InitConfig(
            project_name="test_cli_proj",
            environment=InitEnvironment.CLI,
            output_dir=tmp_path,
            overwrite=True,
        )
        _run_init(cfg)
        project_path = tmp_path / "test_cli_proj"
        assert project_path.is_dir()
        assert (project_path / "config.toml").exists()
        assert (project_path / "data").is_dir()
        assert (project_path / "results").is_dir()

    @pytest.mark.unit
    def test_jupyter_creates_notebook(self, tmp_path: Path) -> None:
        cfg = InitConfig(
            project_name="test_nb_proj",
            environment=InitEnvironment.JUPYTER,
            output_dir=tmp_path,
            overwrite=True,
        )
        _run_init(cfg)
        project_path = tmp_path / "test_nb_proj"
        assert (project_path / "spectrafit_getting_started.ipynb").exists()
        assert not (project_path / "config.toml").exists()

    @pytest.mark.unit
    def test_both_creates_toml_and_notebook(self, tmp_path: Path) -> None:
        cfg = InitConfig(
            project_name="test_both_proj",
            environment=InitEnvironment.BOTH,
            output_dir=tmp_path,
            overwrite=True,
        )
        _run_init(cfg)
        project_path = tmp_path / "test_both_proj"
        assert (project_path / "config.toml").exists()
        assert (project_path / "spectrafit_getting_started.ipynb").exists()

    @pytest.mark.unit
    def test_overwrite_replaces_existing(self, tmp_path: Path) -> None:
        cfg = InitConfig(
            project_name="existing_proj",
            environment=InitEnvironment.CLI,
            output_dir=tmp_path,
            overwrite=True,
        )
        # First creation
        _run_init(cfg)
        toml_path = tmp_path / "existing_proj" / "config.toml"
        first_mtime = toml_path.stat().st_mtime

        # Overwrite
        import time

        time.sleep(0.05)
        _run_init(cfg)
        second_mtime = toml_path.stat().st_mtime
        assert second_mtime >= first_mtime

    @pytest.mark.unit
    def test_cli_creates_toml_v2_format(self, tmp_path: Path) -> None:
        """Config.toml generated by init must be v2 (components key, no fitting key)."""
        try:
            import tomllib  # noqa: PLC0415
        except ImportError:
            import tomli as tomllib  # type: ignore[no-redef]  # noqa: PLC0415

        cfg = InitConfig(
            project_name="test_v2_format",
            environment=InitEnvironment.CLI,
            output_dir=tmp_path,
            overwrite=True,
        )
        _run_init(cfg)
        toml_path = tmp_path / "test_v2_format" / "config.toml"
        assert toml_path.exists()
        with toml_path.open("rb") as fh:
            data = tomllib.load(fh)
        assert "components" in data, "v2 format must have 'components' key"
        assert "fitting" not in data, "v1 banned 'fitting' key must not be present"
        assert len(data["components"]) == 1
        assert data["components"][0]["model"] == "gaussian"
        from spectrafit.cli._types import OutputFormatEnum

        cfg = InitConfig(
            project_name="json_proj",
            environment=InitEnvironment.CLI,
            output_dir=tmp_path,
            overwrite=True,
            fmt=OutputFormatEnum.JSON,
        )
        _run_init(cfg)
        assert (tmp_path / "json_proj" / "config.json").exists()


class TestInitCommandCLI:
    """Integration-style tests for the spectrafit init CLI command."""

    @pytest.mark.unit
    def test_init_cli_flag(self, tmp_path: Path) -> None:
        from spectrafit.cli.main import app

        result = runner.invoke(
            app,
            ["init", "cli_flag_test", "--cli", "--output-dir", str(tmp_path)],
        )
        assert result.exit_code == 0, result.output
        assert (tmp_path / "cli_flag_test" / "config.toml").exists()

    @pytest.mark.unit
    def test_init_mutual_exclusion(self, tmp_path: Path) -> None:
        from spectrafit.cli.main import app

        result = runner.invoke(
            app,
            ["init", "test", "--cli", "--jupyter", "--output-dir", str(tmp_path)],
        )
        assert result.exit_code == 1

    @pytest.mark.unit
    def test_init_jupyter_flag(self, tmp_path: Path) -> None:
        from spectrafit.cli.main import app

        result = runner.invoke(
            app,
            ["init", "nb_test", "--jupyter", "--output-dir", str(tmp_path)],
        )
        assert result.exit_code == 0, result.output
        assert (tmp_path / "nb_test" / "spectrafit_getting_started.ipynb").exists()
