name: Build Devcontainer
on:
  # run on PRs to main branch, if any
  # devcontainer files have changed
  push:
    branches: main
    paths:
      - .devcontainer/**
  pull_request:
    branches:
      - main
    paths:
      - .devcontainer/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and use devcontainer
        uses: devcontainers/ci@v0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_NUMBER: ${{ steps.build_number.outputs.build_number }}
          IS_PR: ${{ github.head_ref }}
          BRANCH: ${{ github.ref }}
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainers-spectrafit
          imageTag: ${{ steps.set_image_tag.outputs.image_tag }}
          runCmd: |
            python --version
            poetry shell
            spectrafit --help
          push: ${{ steps.set_image_push_option.outputs.image_push_option }}
          eventFilterForPush: |
            push
            pull_request
          env: |
            BUILD_NUMBER
            IS_CI=1
            IS_PR
            BRANCH
