name: 🐳 CI - Docker Image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]
  repository_dispatch:
    types: [create-pull-request]

jobs:
  docker:
    if: github.repository == 'Anselmoo/spectrafit'
    # Only if Dockerfile is changed
    name: 🐳 Docker Image Build
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: 🗂️ Filter Dockerfile changes
        uses: dorny/paths-filter@0e4a8c6effa4802afeda77dc8d303f8176d7dfad # v3.0.4
        id: filter
        with:
          filters: |
            docker:
              - 'Dockerfile'
      - name: 🏗️ Build the Docker image for AMD64
        run: |
          docker build . --file Dockerfile --tag spectrafit:$(date +%s)
      # - name: 🏗️ Build the Docker image for ARM64
      #   run: |
      #     docker build . --file Dockerfile --tag spectrafit-arm64:$(date +%s) --platform linux/arm64
