name: 🐳 CI - Docker Image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]
  repository_dispatch:
    types: [create-pull-request]

jobs:
  docker:
    if: github.repository == 'Anselmoo/spectrafit'
    # Only if Dockerfile is changed
    name: 🐳 Docker Image Build
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: 🗂️ Filter Dockerfile changes
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            docker:
              - 'Dockerfile'
      - name: 🏗️ Build the Docker image for AMD64
        run: |
          docker build . --file Dockerfile --tag spectrafit:$(date +%s)
      # - name: 🏗️ Build the Docker image for ARM64
      #   run: |
      #     docker build . --file Dockerfile --tag spectrafit-arm64:$(date +%s) --platform linux/arm64
