name: Package Publishing
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  release:
    types:
      - published
jobs:
  PyPi-Package-Release:
    if: github.repository == 'Anselmoo/spectrafit'
    name: Publish on PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Build and publish
        run: |
          poetry config http-basic.pypi ${{ secrets.TWINE_USERNAME }} ${{ secrets.TWINE_USERNAME }}
          poetry publish --build
        continue-on-error: true
