name: 🚀 CD - Package Publishing
on:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write
  id-token: write

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  PyPi-Package-Release:
    if: github.repository == 'Anselmoo/spectrafit'
    name: 🐍 Publish on PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        name: 🛎️ Checkout repository
      - name: 🐍 Set up uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
        with:
          enable-cache: true
          python-version: "3.13"
      - name: 🏗️ Build package
        run: uv build
      - name: 🚀 Publish package
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TWINE_TOKEN }}
