name: 🔧 CI - Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  update_release_draft:
    if: github.repository == 'Anselmoo/spectrafit'
    name: 📝 Update Release Draft
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@72967cdc98ddd3160f1fc3dff619de365e137dd0 # v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
