name: 🔄 Weekly UV Update

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-dependencies:
    if: github.repository == 'Anselmoo/spectrafit'
    name: 📦 Update Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🛠️ Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
          python-version: "3.10"

      - name: 📅 Set date variable
        id: date
        run: echo "DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: 🌿 Create new branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-dependencies-${{ env.DATE }}

      - name: 📦 Install the dependencies
        run: uv sync --upgrade --all-groups --all-extras

      - name: Update dependencies
        run: uv lock --upgrade  | tee uv-update.log

      - name: Commit changes
        run: |
          git add uv.lock
          if git diff-index --quiet HEAD; then
            echo "No changes detected, creating an empty commit."
            git commit --allow-empty -m "chore(deps): :arrows_counterclockwise: no updates for ${{ env.DATE }}"
          else
            echo "Changes detected, creating a commit with update log."
            if [ -f uv-update.log ]; then
              update_log=$(cat uv-update.log)
            else
              update_log="No update log available."
            fi
            git commit -m "$(echo -e "chore(deps): :arrows_counterclockwise: update dependencies ${{ env.DATE }}\n\n$update_log")"
          fi

      - name: 📤 Push changes
        run: |
          gh auth setup-git
          git push -f origin update-dependencies-${{ env.DATE }}
        env:
          GITHUB_TOKEN: ${{ secrets.WEEKLY_UPDATE }}

      - name: 🔀 Create Pull Request via gh
        id: create_pr
        run: |
          update_log=$(cat uv-update.log 2>/dev/null || echo "No update log available")
          pr_url=$(gh pr create --title "chore(deps): :arrows_counterclockwise: update dependencies $(date +%Y%m%d%H%M)" \
          --body "This is an auto-generated pull request to update dependencies in \`uv.lock\`.\n\nUpdate Log:\n\`\`\`\n$update_log\n\`\`\`" \
          --base main \
          --head update-dependencies-$(date +%Y%m%d%H%M))
          echo "pr_url=$pr_url" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.WEEKLY_UPDATE }}

      - name: 🏷️ Add Label to Pull Request
        run: |
          pr_number=$(gh pr view --json number --jq '.number' "${{ steps.create_pr.outputs.pr_url }}")
          gh pr edit $pr_number --add-label "weekly-update"
        env:
          GITHUB_TOKEN: ${{ secrets.WEEKLY_UPDATE }}

      - name: 🔄 Merge Pull Request via gh
        run: |
          gh pr merge update-dependencies-${{ env.DATE }} --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.WEEKLY_UPDATE }}
